In [2]:
# Standard library imports
import logging
import warnings
from pathlib import Path

# Third-party imports
import pandas as pd
import wrds

# Suppress warnings
warnings.filterwarnings("ignore", category=FutureWarning)
warnings.filterwarnings("ignore")

from settings import config
from pull_taq import get_taq_nbbo, get_taq_wct

In [3]:
# Change default pandas display options

pd.options.display.max_columns = 30
pd.options.display.max_colwidth = 200
pd.set_option('display.float_format', lambda x: '%.4f' % x)
pd.set_option('display.expand_frame_repr', False)

# Global variables
RAW_DATA_DIR = Path(config("RAW_DATA_DIR"))
RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR = Path(config("OUTPUT_DIR"))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
LOG_PATH = Path(config("LOG_DIR")) / "log.log"
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
WRDS_USERNAME = config("WRDS_USERNAME")

# Global Constants

# Set up Logging:
logging.basicConfig(
    filename=LOG_PATH,
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S"
)
from pull_taq import get_taq_nbbo, get_taq_wct

In [4]:
quotes = get_taq_nbbo(('SPY'), date='2024-02-27', use_bars=False)
quotes

        ticker        date           time_m  time_m_nano  best_bid  best_bidsizeshares  best_ask  best_asksizeshares
0          SPY  2024-02-27  09:30:00.000143          104  506.6900                2200  506.7100                 400
1          SPY  2024-02-27  09:30:00.000339          688  506.6900                2300  506.7100                 400
2          SPY  2024-02-27  09:30:00.000489          704  506.6900                2200  506.7100                 400
3          SPY  2024-02-27  09:30:00.000514          792  506.6900                2200  506.7100                 500
4          SPY  2024-02-27  09:30:00.000935          656  506.6900                2100  506.7100                 500
...        ...         ...              ...          ...       ...                 ...       ...                 ...
2310851    SPY  2024-02-27  15:59:59.999851            8  506.8600                1100  506.8800               24300
2310852    SPY  2024-02-27  15:59:59.999856          872  506.8600                1100  506.8800               28800
2310853    SPY  2024-02-27  15:59:59.999876          840  506.8600                1100  506.8700                 200
2310854    SPY  2024-02-27  15:59:59.999881          960  506.8600                1100  506.8700                 400
2310855    SPY  2024-02-27  15:59:59.999991          296  506.8600                1100  506.8700                 200

[2310856 rows x 8 columns]

In [5]:
trades = get_taq_wct(('SPY'), date='2024-02-27')
trades

Loading library list...
Done

       ticker        date           time_m    price  size trade_correction
0         SPY  2024-02-27  09:30:00.000932 506.6900   100               00
1         SPY  2024-02-27  09:30:00.009106 506.7100     2               00
2         SPY  2024-02-27  09:30:00.009942 506.7100    10               00
3         SPY  2024-02-27  09:30:00.010005 506.7000     1               00
4         SPY  2024-02-27  09:30:00.010116 506.7000   100               00
...       ...         ...              ...      ...   ...              ...
388782    SPY  2024-02-27  15:59:59.991101 506.9000   100               00
388783    SPY  2024-02-27  15:59:59.991101 506.9000   100               00
388784    SPY  2024-02-27  15:59:59.999350 506.8700   100               00
388785    SPY  2024-02-27  15:59:59.999482 506.8700   100               00
388786    SPY  2024-02-27  15:59:59.999482 506.8700   100               00

[388787 rows x 6 columns]